### ISSUE TITLE
raise error when parser fails

### ISSUE THREAD

**Issue by logicminds** [jm/toml#47]
https://github.com/jm/toml/blob/master/lib/toml/parser.rb#L11

I want to be able to catch this error and do something more intelligent when I am using this library in my project.

Can you just remove the code?

**Comment by ayng** [comment]
Another reason to remove this code is to avoid relying on the interface of `Parslet::ParseFailed`, in this case the attribute `.cause`. This became a problem in the 0.2.0 release of this gem, when the parslet dependency version was [bumped from 1.6.2 to 1.8.0](https://github.com/jm/toml/commit/aaea90e2232de5177e2b96a7e21006fbeb2c3be6).

Starting from parslet 1.8.0, `.cause` was renamed to `.parse_failure_cause` ([commit](https://github.com/kschiess/parslet/commit/8b3b9d268309222f48e9843de65f65a6abef8031)).

So when you try to parse some invalid TOML, instead of `ParseFailed` you get `NoMethodError` as ruby tries to call `ascii_tree` on `nil`.
